import { DataSource } from 'typeorm';
import { config } from 'dotenv';
import {
  UserEntity,
  ApplicationEntity,
  ApplicationStatusHistoryEntity,
  ApplicationAnswerEntity,
  OrganizationEntity,
  SubscriptionEntity,
  JobEntity,
  JobQuestionEntity,
  ResumeEntity,
  WaitlistEntity,
  ChatEntity,
  MessageEntity,
  SavedJobEntity,
  EventEntity,
  EventNoteEntity,
  EventParticipantEntity,
  SavedCandidateEntity,
  CandidateTagEntity,
  CandidateTagAssignmentEntity,
  MessageTemplateEntity,
  ActivityLogEntity,
  ApiKeyEntity,
  AiCredentialEntity,
  SalarySubmissionEntity,
} from './src/infrastructure/database/orm';
import { JobTemplateEntity } from './src/infrastructure/database/orm/job-template.entity';
import { OrganizationMemberEntity } from './src/infrastructure/database/orm/organization-member.entity';
import { PipelineStageEntity } from './src/infrastructure/database/orm/pipeline-stage.entity';
import { SavedSearchEntity } from './src/infrastructure/database/orm/saved-search.entity';

config();

export const AppDataSource = new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST || 'localhost',
  port: parseInt(process.env.DB_PORT || '5432'),
  username: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  entities: [
    UserEntity,
    ApplicationEntity,
    ApplicationStatusHistoryEntity,
    ApplicationAnswerEntity,
    OrganizationEntity,
    SubscriptionEntity,
    JobEntity,
    JobQuestionEntity,
    ResumeEntity,
    WaitlistEntity,
    ChatEntity,
    MessageEntity,
    SavedJobEntity,
    EventEntity,
    EventNoteEntity,
    EventParticipantEntity,
    JobTemplateEntity,
    SavedCandidateEntity,
    CandidateTagEntity,
    CandidateTagAssignmentEntity,
    MessageTemplateEntity,
    ActivityLogEntity,
    ApiKeyEntity,
    AiCredentialEntity,
    OrganizationMemberEntity,
    PipelineStageEntity,
    SavedSearchEntity,
    SalarySubmissionEntity,
  ],
  migrations: ['src/infrastructure/database/migrations/*.ts'],
  migrationsTableName: 'migrations',
  synchronize: false,
  logging: process.env.NODE_ENV === 'development',
});
